
#
#spring:
#  application:
#    name: api-gateway
#  zipkin:
#    base-url: http://localhost:9411/
#  cloud:
#    gateway:
#      routes:
#        - id: customerService
#          uri: lb://customerService
#          predicates:
#            - Path=/customers/**
#        - id: borrowingService
#          uri: lb://borrowingService
#          predicates:
#            - Path=/borrowing/**
#        - id: BookQueryService
#          uri: lb://BookQueryService
#          predicates:
#            - Path=/bookquery/**
#        - id: BookCommandService
#          uri: lb://BookCommandService
#          predicates:
#            - Path=/bookcommand/**
#        - id: ReviewService
#          uri: lb://ReviewService
#          predicates:
#            - Path=/reviews/**
#
#server:
#  port: 8079
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#sleuth:
#  sampler:
#    probability: 1 #100% (default = 10%)